// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/auth/login.ts";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/test/[id].ts";
import * as $4 from "./routes/api/test/index.ts";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/working/_middleware.ts";
import * as $7 from "./routes/working/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Joke.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/auth/login.ts": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/test/[id].ts": $3,
    "./routes/api/test/index.ts": $4,
    "./routes/index.tsx": $5,
    "./routes/working/_middleware.ts": $6,
    "./routes/working/index.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Joke.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
